<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE company SYSTEM "external.dtd" > -->
<!DOCTYPE company [
<!ELEMENT company (department*)>
<!ELEMENT department (employees*)>
<!ELEMENT employees (department-name*)>
<!ELEMENT department-name (employee-id,employee-name,employee-address)>
<!ELEMENT employee-id (#PCDATA)>
<!ELEMENT employee-name (#PCDATA)>
<!ELEMENT employee-address (#PCDATA)>
]>
<company>
    <department>
       <employees>
          	<department-name>
             <employee-id>1</employee-id>
            <employee-name>Suraj</employee-name>
            <employee-address>Pune</employee-address>

            <employee-id>2</employee-id>
            <employee-name>Amol</employee-name>
            <employee-address>Mumbai</employee-address>

            <employee-id>3</employee-id>
            <employee-name>mahesh</employee-name>
            <employee-address>Nagar</employee-address>
          
          </department-name>
          	<department-name>
          
          	<employee-id>101</employee-id>
            <employee-name>Yesh</employee-name>
            <employee-address>Pune</employee-address>

            <employee-id>102</employee-id>
            <employee-name>Mohan</employee-name>
            <employee-address>Mumbai</employee-address>

            <employee-id>103</employee-id>
            <employee-name>Kiran</employee-name>
            <employee-address>Nagar</employee-address>
          </department-name>
        </employees>
      	
    </department>
  
</company>
